theme:
remote_theme: "aisocietylab/group-website-pages"
minimal_mistakes_skin: "air" # "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
title: "Fuzzy Neural Network for News Recommendation"
name: "Kevin Innerebner"
description: "Modeling Behavioral Patterns in News Recommendations Using Fuzzy Neural Networks"
url: https://aisocietylab.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
# the subpath of your site, e.g. "/blog" (for github.io this should be your repository name!)
baseurl: "/FNN4NewsRecommendation"
repository: "aisocietylab/FNN4NewsRecommendation" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
atom_feed:
  hide: true # true, false (default)
google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true
# SEO Related
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aisocietylab"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  # url:
    #- label: "Facebook"
    #  icon: "fab fa-fw fa-facebook-square"
    #  # url:
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  # url:
    #- label: "GitLab"
    #  icon: "fab fa-fw fa-gitlab"
    #  # url:
    #- label: "Bitbucket"
    #  icon: "fab fa-fw fa-bitbucket"
    #  # url:
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  # url:
